sudo: required
language: python
python:
  - "2.7"
services:
  - docker
  - redis-server
install:
  - cd backend
  - pip install flask
  - python setup.py install
  - pip install coveralls
script:
  - coverage run --source=poliglo_server setup.py test
  - sudo service redis-server stop
  - cd .. && ./unit_tests.sh
after_success:
  - cd backend && coveralls
