version: '2'
services:
  server:
    build: .
    ports:
      - 9015:9015
    volumes:
      - ./backend/:/src/backend
      - ./examples:/src/examples
    environment:
      - CONFIG_PATH=/src/examples/tests/config.docker.json
      - WORKFLOWS_PATH=/src/examples/tests/workflows
      - POLIGLO_WORKER_URL=http://worker:9001
      - TEST_REDIS_HOST=redis
    depends_on:
      - redis
  monitor:
    build: monitor
    volumes:
      - /src/monitor/node_modules
      - /src/monitor/bower_components
      - ./monitor:/src/monitor
    depends_on:
      - server
    ports:
      - 9000:9000
  worker:
    build: deployment
    volumes:
      - ./deployment:/src/deployment
      - ./examples:/src/examples
      - ./workers:/src/workers
    environment:
      - POLIGLO_SERVER_URL=http://server:9015
      - WORKERS_PATHS=/src/examples/tests/workers/
      - SUPERVISOR_LOG_PATH=/tmp/poliglo_supervisor_logs
      - TEST_REDIS_HOST=redis
    depends_on:
      - server
      - redis
    ports:
      - 9001:9001
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
